### ISSUE TITLE
Hotkeys displayed in the context menu are MacOS-specific

### ISSUE THREAD

**Issue by donaldoakes** [ply-ct/vscode-ply#23]
For example, the Cut command the screenshot below should show in Windows
<img width="281" alt="Screen Shot 2020-12-03 at 4 41 41 PM" src="https://user-images.githubusercontent.com/19718743/101103678-aaa8a180-3586-11eb-8949-02eb13059c1a.png">

**Comment by magrawa** [comment]
Fixed as part of https://github.com/ply-ct/vscode-ply/commit/0e7fe3b5c5488d2c5855ab424250e5b6919ccd3d
