### ISSUE TITLE
When running a newly created flow, don't get the "Submit" option (& the test fails)

### ISSUE THREAD

**Issue by rwhitehead64** [ply-ct/vscode-ply#64]
Given I've created a new test-flow (it contains just the  "Start" and "Stop" steps)
When I hit the ">" button to run the flow ("Run your flow" section) ...
      ... _I don't get the prompt-option that says "Submit without verifying"_
      ... _And then the test fails, with the message,_ 

"Expected result file not found: c:/Users/richw/Ply/Ply-CT/Rich_Test/results/expected/get-movies.ymlError: 
 Expected result file not found: c:/Users/richw/Ply/Ply-CT/Rich_Test/results/expected/get-movies.yml"

**Comment by donaldoakes** [comment]
In fact, even non-newly created flows exhibit this same behavior. Fixed with #4b4898a.
